### ISSUE TITLE
An issue about CPLEX 12.8 `-ldl` on Mac OS

### ISSUE THREAD

**Issue by CicoZhang** [ls-cwi/heinz#13]
I am still using the Release 2.0.
I use the same fix as https://github.com/ls-cwi/heinz/blob/master/CMakeLists.txt#L167. It works on Ubuntu 18.04; but unfortunately not in Mac OS; I get the error as follows:
```
char> > in libemon.a(arg_parser.cc.o)
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [print] Error 1
make[1]: *** [CMakeFiles/print.dir/all] Error 2
make: *** [all] Error 2
BUILD START: heinz-2.0-0
    (actual version deferred until further download or env creation)
```
The full report can be found [here](https://circleci.com/gh/bioconda/bioconda-recipes/10095)
@guwek Have you encountered it before?
